name = "werdmail"
main = "worker.js"
compatibility_date = "2025-07-08"
node_compat = true

[vars]
BOT_TOKEN = "8069861632:AAEJObSQNWjxm_MsiCgmzad_-UEOeNDmwJY"
FIREBASE_PROJECT = "werdmail-fd79b"

[[kv_namespaces]]
binding = "WERDMAIL_STATE"
id = "55648fedc3a642fcb2e04cc8fa3a9e3a"
